In [1]:
import pandas as pd
import csv
import numpy as np

In [102]:
ny_org = open('ny_org_results_check_ln.csv','r', encoding='latin1')
ny_auth = open('ny_auth_results_check_ln.csv','r', encoding='latin1')

chi_org = open('chi_org_results_check_ln.csv','r', encoding='latin1')
chi_auth = open('chi_auth_results_check_ln.csv','r', encoding='latin1')

In [103]:
ny_org_df = pd.read_csv(ny_org)
ny_auth_df = pd.read_csv(ny_auth)

chi_org_df = pd.read_csv(chi_org)
chi_auth_df = pd.read_csv(chi_auth)

In [104]:
ny_org_df.head(25)

,Unnamed: 0,ny org,count,pull for Ben (focused),pull for Ben (broad)
0,238,Birth Control League,0,NaN,NaN
1,229,Brooklyn Woman Suffrage Association,0,NaN,NaN
2,175,Brooklyn Woman's Health Protective Association,0,NaN,NaN
3,98,College Settlement/University Settlement,0,NaN,NaN
4,17,Communist Party,0,NaN,NaN
5,40,Congress of American Women,0,NaN,NaN
6,100,Congress of Racial Equality,0,NaN,NaN
7,251,Congress of Racial Equality,13,1.0,1.0
8,43,Congressional Union/National Woman's Party,0,NaN,NaN
9,207,Consumers' League of New York City,0,NaN,NaN
10,90,Consumers' League of New York City,45,1.0,1.0
11,205,Consumers' League of New York City Brooklyn Au...,2,1.0,1.0
12,63,Consumers' Protective Committee,0,NaN,NaN
13,189,Daughters of Bilitis,0,NaN,NaN
14,203,Dodge's Evenings,0,NaN,NaN
15,133,Equal Franchise Society,0,NaN,NaN
16,172,Equal Franchise Society,3,NaN,1.0
17,165,Equal Franchise Society (New York),4,1.0,1.0
18,149,Equality League of Self-Supporting Women,0,NaN,NaN
19,11,Freedom Summer,0,NaN,NaN
20,183,Greenwich House,0,NaN,NaN
21,260,"Greenwich House (New York, N.Y.)",3,1.0,1.0
22,136,Henry Street Settlement,0,NaN,NaN
23,164,"Henry Street Settlement (New York, N.Y.)",9,1.0,1.0
24,254,"Henry Street Settlement, New York Hamilton Hou...",1,1.0,1.0

In [105]:
ny_org_pull_list = []

for i in ny_org_df.index:
    ben_f = ny_org_df['pull for Ben (focused)'][i]
    ben_b = ny_org_df['pull for Ben (broad)'][i]
    name = ny_org_df['ny org'][i]
    nan_test_f = pd.isnull(ben_f)
    nan_test_b = pd.isnull(ben_b)
    # print(ben)
    if nan_test_f == False or nan_test_b == False:
        ny_org_pull_list.append(name)

print(len(ny_org_pull_list))

54

In [107]:
# ny_org_pull_list

In [109]:
ny_auth_df.columns = ['Unnamed: 0', 'ny person', 'count', 'pull for Ben (focused)', 'notes']

In [110]:
ny_auth_df.head(15)

,Unnamed: 0,ny person,count,pull for Ben (focused),notes
0,10.0,Ann Forer,0,NaN,NaN
1,65.0,Ann Snitow,0,NaN,NaN
2,143.0,Anne Koedt,0,NaN,NaN
3,37.0,"Anthony, Katherine",0,NaN,NaN
4,51.0,"Anthony, Katherine M. (Katherine Miner)",1,1.0,NaN
5,92.0,"Arthur, Helen",0,NaN,NaN
6,2.0,"Atkinson, Ti-Grace.",1,1.0,NaN
7,14.0,"Austin, Mary Hunter",0,NaN,NaN
8,45.0,"Austin, Mary Hunter 1868-1934",119,1.0,NaN
9,23.0,"Austin, Mary Hunter 1868-1934 The young woman ...",1,1.0,NaN
10,59.0,"Baker, Sara Josephine",0,NaN,NaN
11,133.0,Barbara Easton,0,NaN,NaN
12,104.0,"Brown, Rita Mae",4,1.0,NaN
13,76.0,"Brown, Rita Mae.",35,1.0,NaN
14,25.0,"Brownmiller, Susan",1,1.0,NaN

In [111]:
ny_auth_pull_list = []

for i in ny_auth_df.index:
    ben_f = ny_auth_df['pull for Ben (focused)'][i]
    # ben_b = ny_auth_df['pull for Ben (broad)'][i]
    name = ny_auth_df['ny person'][i]
    nan_test_f = pd.isnull(ben_f)
    nan_test_b = pd.isnull(ben_b)
    # print(ben)
    if nan_test_f == False: # or nan_test_b == False:
        ny_auth_pull_list.append(name)

print(len(ny_auth_pull_list))

53

In [115]:
# ny_auth_pull_list = ny_auth_pull_list[:-2]
# ny_auth_pull_list
print(len(ny_auth_pull_list))

51

In [116]:
chi_org_df.head(15)

,Unnamed: 0,chicago org,count,pull for Ben (focused),pull for Ben (broad)
0,156,AFL Ladies' Federal Union,0,NaN,NaN
1,365,Alpha Suffrage Club,0,NaN,NaN
2,363,Amalgamated Clothing Workers of America,0,NaN,NaN
3,331,Amalgamated Clothing Workers of America,86,NaN,1.0
4,341,Amalgamated Clothing Workers of America Board ...,1,NaN,1.0
5,31,Amalgamated Clothing Workers of America Chicag...,14,1.0,1.0
6,209,Amalgamated Clothing Workers of America Cincin...,2,NaN,NaN
7,321,Amalgamated Clothing Workers of America Conven...,63,NaN,1.0
8,327,Amalgamated Clothing Workers of America Educat...,6,NaN,1.0
9,132,Amalgamated Clothing Workers of America Genera...,34,NaN,1.0
10,229,Amalgamated Clothing Workers of America New Yo...,2,1.0,1.0
11,96,Amalgamated Clothing Workers of America Resear...,1,NaN,1.0
12,81,Amalgamated Clothing Workers of America Resear...,9,NaN,1.0
13,227,Amalgamated Clothing Workers of America Resear...,1,NaN,1.0
14,257,Amalgamated Clothing Workers of America defend...,1,NaN,1.0

In [117]:
chi_org_pull_list = []

for i in chi_org_df.index:
    ben_f = chi_org_df['pull for Ben (focused)'][i]
    ben_b = chi_org_df['pull for Ben (broad)'][i]
    name = chi_org_df['chicago org'][i]
    nan_test_f = pd.isnull(ben_f)
    nan_test_b = pd.isnull(ben_b)
    # print(ben)
    if nan_test_f == False or nan_test_b == False:
        chi_org_pull_list.append(name)

print(len(chi_org_pull_list))

72

In [118]:
chi_auth_df.head(15)

,Unnamed: 0,chicago person,count,pull for Ben
0,121,Elizabeth Gurley Flynn,0,NaN
1,78,"Abbott, Edith 1876-1957",96,1.0
2,17,"Abbott, Edith 1876-1957. [from old catalog]",1,1.0
3,132,"Abbott, Edith.",2,1.0
4,10,"Abbott, Grace 1878-1939",22,1.0
5,6,"Addams, Jane 1860-1935",148,1.0
6,57,Alice Hamilton,0,NaN
7,102,Alzina Stevens,0,NaN
8,32,Amy Kesselman,0,NaN
9,70,"Anderson, Mary 1859-1940",11,1.0
10,67,"Anderson, Mary 1872-1964",4,NaN
11,51,"Anderson, Mary 1922-",2,NaN
12,42,"Anderson, Mary 1929-",5,NaN
13,9,"Anderson, Mary Alice 1947-",1,NaN
14,66,"Anderson, Mary Ananell.",3,NaN

In [119]:
chi_auth_pull_list = []

for i in chi_auth_df.index:
    ben_f = chi_auth_df['pull for Ben'][i]
    # ben_b = chi_auth_df['pull for Ben (broad)'][i]
    name = chi_auth_df['chicago person'][i]
    nan_test_f = pd.isnull(ben_f)
    nan_test_b = pd.isnull(ben_b)
    # print(ben)
    if nan_test_f == False: # or nan_test_b == False:
        chi_auth_pull_list.append(name)

print(len(chi_auth_pull_list))

35

In [63]:
# with open('chi_auth_pull_list.txt','w') as f:
#     for item in chi_auth_pull_list:
#         f.write(item + '\n')
        
# with open('chi_org_pull_list.txt','w') as g:
#     for item in chi_org_pull_list:
#         g.write(item + '\n')
        
# with open('ny_auth_pull_list.txt','w') as h:
#     for item in ny_auth_pull_list:
#         h.write(item + '\n')
        
# with open('ny_org_pull_list.txt','w') as j:
#     for item in ny_org_pull_list:
#         j.write(item + '\n')

In [120]:
ny_org_ed = open('newyork_org_results.csv','r', encoding='latin1')
ny_auth_ed = open('newyork_author_results.csv','r', encoding='latin1')

chi_org_ed = open('chicago_org_results.csv','r', encoding='latin1')
chi_auth_ed = open('chicago_names_results.csv','r', encoding='latin1')

In [121]:
ny_org_df_ed = pd.read_csv(ny_org_ed)
ny_org_df_ed.head(15)

,htid,title,org
0,coo.31924001835820,The outside system of production in the women'...,International Ladies' Garment Workers' Union
1,coo.31924002005183,"Know your schools, Tompkins County, New York",League of Women Voters of Tompkins County (Tom...
2,coo.31924002335606,Twenty-fifth anniversary testimonial to Harry ...,International Ladies' Garment Workers' Union L...
3,coo.31924002403206,"Official report of the Strike committee, Chica...",Women's Trade Union League of Chicago
4,coo.31924003667635,Annual report,International Ladies' Garment Workers' Union U...
5,coo.31924000838536,Our aim,International Ladies' Garment Workers' Union L...
6,coo.31924003806647,Washington consumers' checkbook,National Consumers' League
7,coo.31924001693591,Comments on the New York State unemployment in...,International Ladies' Garment Workers' Union
8,coo.31924002306748,"In the Supreme Court of the United States, Oct...",International Ladies' Garment Workers' Union
9,coo.31924003833435,The Ladies' garment worker,International Ladies' Garment Workers' Union
10,coo.31924014071959,Know your county,League of Women Voters (U.S.)
11,coo.31924003670282,Convention report,Women's Trade Union League of New York
12,coo.31924050114770,Report and proceedings,International Ladies' Garment Workers' Union C...
13,coo.31924003365503,Local government in Tompkins County,League of Women Voters of Tompkins County (Tom...
14,coo.31924003806647,How to prepare evaluative guides to job traini...,National Consumers' League

In [122]:
ny_org_pull_dict = {}

for i in ny_org_df_ed.index:
    org = ny_org_df_ed['org'][i]
    vol = ny_org_df_ed['htid'][i]
    if org in ny_org_pull_dict:
        ny_org_pull_dict[org] += [vol]
        
    elif org in ny_org_pull_list:
        ny_org_pull_dict[org] = [vol]
        
print(len(ny_org_pull_dict))

11

In [134]:
ny_org_pull_dict

{'Greenwich House (New York, N.Y.) ': ['mdp.39015034368798',
  'mdp.39015028060609',
  'umn.31951001519095i'],
 'Henry Street Settlement (New York, N.Y.) ': ['hvd.32044096984315',
  'mdp.39015032973870',
  'uc1.32106001402830',
  'uc1.32106001402830',
  'uc1.b2825126',
  'uiug.30112063825167',
  'uiuo.ark:/13960/t3033k24n',
  'mdp.39015032973870',
  'uc1.32106001402830'],
 'Henry Street Settlement, New York Hamilton House. ': ['uc1.b3865194'],
 "International Ladies' Garment Workers' Union Local 89 (New York, N.Y.) ": ['inu.30000055098549',
  'inu.30000055098549',
  'inu.30000055098549'],
 "International Ladies' Garment Workers' Union Local 91 (New York, N.Y.) ": ['coo.31924002335606',
  'umn.31951002031948a'],
 "International Ladies' Garment Workers' Union Local 91, New York. ": ['coo.31924000838536',
  'coo.31924054286210',
  'coo.31924054286228',
  'coo.31924054286236',
  'coo.31924054286202'],
 'League of Women Voters of Albany County (Albany County, N.Y.) ': ['coo.31924052338997'],
 'League of Women Voters of Cook County (Cook County, Ill.) ': ['ien.35556020525689',
  'ien.35556018017061',
  'ien.35556020525689',
  'ien.35556021878988',
  'ien.35556022999098',
  'ien.35556026700013',
  'ien.35556021807136',
  'ien.35556021885181',
  'ien.35556021878988',
  'ien.35556022999098',
  'ien.35556026675447',
  'ien.35556026356584',
  'ien.35556026675447',
  'ien.35556031552870',
  'ien.35556031552870',
  'ien.35556021807136',
  'ien.35556021885181',
  'ien.35556026356584',
  'ien.35556026700013'],
 'League of Women Voters of Cook County, Ill ': ['mdp.39015082092431'],
 'Progressive Party National Convention: (1st : 1912 : Chicago, Ill.) ': ['umn.31951001536118z'],
 'Sorosis (New York, N.Y.) ': ['hvd.32044087387908',
  'hvd.32044013641089',
  'hvd.hn6ixd']}

In [123]:
ny_auth_df_ed = pd.read_csv(ny_auth_ed)
ny_auth_df_ed.head(15)

,htid,title,person
0,ÈÀaeu.ark:/13960/t4dn5fd4r,Concerning children,"Gilman, Charlotte Perkins 1860-1935"
1,aeu.ark:/13960/t89g7140g,The social significance of modern drama,"Goldman, Emma 1869-1940"
2,chi.105719338,Psychology of the unconscious a study of the t...,"Hinkle, Beatrice M."
3,aeu.ark:/13960/t89g7140g,The social significance of the modern drama,"Goldman, Emma 1869-1940"
4,aeu.ark:/13960/t4rj69w6s,The visioning a novel,"Glaspell, Susan 1882-1948"
5,chi.14486630,Suppressed desires,"Glaspell, Susan 1876-1948"
6,coo1.ark:/13960/t59c7h793,The arrow-maker a drama in three acts,"Austin, Mary Hunter 1868-1934"
7,aeu.ark:/13960/t5x64s13j,Ladies must live,"Miller, Alice Duer 1874-1942"
8,chi.105719338,Wandlungen und Symbole der Libido. English,"Hinkle, Beatrice M."
9,chi.15478087,Just around the corner romance en casserole,"Hurst, Fannie 1889-1968"
10,coo.31924002303646,Executive careers for women,"Maule, Frances 1879-1966"
11,coo.31924013826734,Love is a challenge,"Seabury, Florence (Guy) Mrs"
12,coo.31924073944716,Rubyfruit jungle,"Brown, Rita Mae."
13,coo1.ark:/13960/t7kp8kn3x,Are women people? A book of rhymes for suffrag...,"Miller, Alice Duer 1874-1942"
14,coo.31924106110608,The Forerunner,"Gilman, Charlotte Perkins 1860-1935"

In [124]:
ny_auth_pull_dict = {}

for i in ny_auth_df_ed.index:
    p = ny_auth_df_ed['person'][i]
    vol = ny_auth_df_ed['htid'][i]
    if p in ny_auth_pull_dict:
        ny_auth_pull_dict[p] += [vol]
        
    elif p in ny_auth_pull_list:
        ny_auth_pull_dict[p] = [vol]
        
print(len(ny_auth_pull_dict))

51

In [89]:
# ny_auth_pull_dict

In [125]:
chi_org_df_ed = pd.read_csv(chi_org_ed)
chi_org_df_ed.head(15)

,htid,title,org
0,ÈÀcoo.31924002005183,"Know your schools, Tompkins County, New York",League of Women Voters of Tompkins County (Tom...
1,coo.31924002334971,"Anniversary journal, on the occasion of the ce...","Amalgamated Clothing Workers of America, Local..."
2,coo.31924000810220,Proceedings of the ... Biennial Convention of ...,Amalgamated Clothing Workers of America Conven...
3,coo.31924002403206,"Official report of the Strike committee, Chica...",Women's Trade Union League of Chicago
4,coo.31924001734064,Resolutions and proceedings 1977 convention of...,"Coalition of Labor Union Women Convention, Was..."
5,coo.31924003755877,Directory of Arizona labor organizations,Coalition of Labor Union Women (U.S.) Maricopa...
6,coo.31924003365503,Local government in Tompkins County,League of Women Voters of Tompkins County (Tom...
7,coo.31924001273147,A commitment to children the report of the Coa...,Coalition of Labor Union Women.
8,chi.40798587,Proceedings of the second annual convention of...,Industrial Workers of the World Convention (2n...
9,coo.31924014071959,Know your county,League of Women Voters (U.S.)
10,coo.31924002334948,The wage policies of the Amalgamated Clothing ...,Amalgamated Clothing Workers of America
11,chi.56503045,The handbook of the Young women's Christian as...,Young Women's Christian Association of the U.S...
12,coo.31924003670282,Convention report,Women's Trade Union League of New York
13,coo.31924000810220,Documentary history of the Amalgamated Clothin...,Amalgamated Clothing Workers of America Conven...
14,coo.31924050122278,"Women and employment, a Canadian perspective",Young Women's Christian Association of Metropo...

In [129]:
chi_org_pull_dict = {}

for i in chi_org_df_ed.index:
    org = chi_org_df_ed['org'][i]
    vol = chi_org_df_ed['htid'][i]
    if org in chi_org_pull_dict:
        chi_org_pull_dict[org] += [vol]
        
    elif org in chi_org_pull_list:
        chi_org_pull_dict[org] = [vol]
        
print(len(chi_org_pull_dict))

13

In [131]:
# chi_org_pull_dict

In [126]:
chi_auth_df_ed = pd.read_csv(chi_auth_ed)
chi_auth_df_ed.head(15)

,htid,title,person
0,ÈÀcoo.31924003252073,Studies in protein and amino acid nutrition us...,"Anderson, Mary Eldrid 1926-"
1,coo.31924014531028,"The Child, the clinic and the court","Addams, Jane 1860-1935"
2,coo1.ark:/13960/t05x2w09h,A summary of juvenile-court legislation in the...,"Breckinridge, Sophonisba Preston 1866-1948"
3,coo1.ark:/13960/t0ks78j5j,The delinquent child and the home,"Abbott, Edith 1876-1957"
4,coo.31924003585589,Windowless offices user satisfaction and adapt...,"Anderson, Mary Ann 1940-"
5,coo1.ark:/13960/t5db8mk3w,Juvenile court laws in the United States a sum...,"Abbott, Grace 1878-1939"
6,coo1.ark:/13960/t1jh4rq9k,The Social application of religion,"Addams, Jane 1860-1935"
7,aeu.ark:/13960/t6058td8c,The long road of woman's memory,"Addams, Jane 1860-1935"
8,chi.11932228,"The child, and other verses","Anderson, Mary Louisa."
9,coo1.ark:/13960/t1zc8gz98,The long road of woman's memory,"Addams, Jane 1860-1935"
10,chi.21184561,Women in industry a study in American economic...,"Abbott, Edith 1876-1957"
11,coo.31924073957254,Community-based research on child mortality in...,"Booth, Heather 1950-"
12,coo1.ark:/13960/t7tm7s30w,Women in industry a study in American economic...,"Abbott, Edith 1876-1957"
13,coo.31924073957254,Measurement and meaning community-based resear...,"Booth, Heather 1950-"
14,emu.010000667705,Lynch law in Georgia a six-weeks' record in th...,"Wells-Barnett, Ida B. 1862-1931"

In [127]:
chi_auth_pull_dict = {}

for i in chi_auth_df_ed.index:
    p = chi_auth_df_ed['person'][i]
    vol = chi_auth_df_ed['htid'][i]
    if p in chi_auth_pull_dict:
        chi_auth_pull_dict[p] += [vol]
        
    elif p in chi_auth_pull_list:
        chi_auth_pull_dict[p] = [vol]
        
print(len(chi_auth_pull_dict))

35

In [99]:
# chi_auth_pull_dict

In [136]:
# ny_org_cl_dict = {}

# for k, v in ny_org_pull_dict.items():
#     print('keys: ', k)
#     print('vals: ', v)
#     for item in v:
#         ny_org_cl_dict[k] = item
        
# print(len(ny_org_cl_dict))

x = [item[0] for item in ny_org_pull_dict.items()]
ny_org_cl_df = pd.DataFrame({'org': x[0], 'htid': ny_org_pull_dict[x[0]]})
for row in x[1:]:
    df2 = pd.DataFrame({'org': row, 'htid': ny_org_pull_dict[row]})
    ny_org_cl_df = pd.concat([ny_org_cl_df, df2])
    
ny_org_cl_df.head(15)

,htid,org
0,hvd.32044096984315,"Henry Street Settlement (New York, N.Y.)"
1,mdp.39015032973870,"Henry Street Settlement (New York, N.Y.)"
2,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
3,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
4,uc1.b2825126,"Henry Street Settlement (New York, N.Y.)"
5,uiug.30112063825167,"Henry Street Settlement (New York, N.Y.)"
6,uiuo.ark:/13960/t3033k24n,"Henry Street Settlement (New York, N.Y.)"
7,mdp.39015032973870,"Henry Street Settlement (New York, N.Y.)"
8,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
0,mdp.39015082092431,"League of Women Voters of Cook County, Ill"
0,umn.31951001536118z,Progressive Party National Convention: (1st : ...
0,coo.31924002335606,International Ladies' Garment Workers' Union L...
1,umn.31951002031948a,International Ladies' Garment Workers' Union L...
0,uc1.b3865194,"Henry Street Settlement, New York Hamilton Hou..."
0,coo.31924052338997,League of Women Voters of Albany County (Alban...

In [137]:
ny_org_cl_df.shape

(48, 2)

In [138]:
x = [item[0] for item in ny_auth_pull_dict.items()]
ny_auth_cl_df = pd.DataFrame({'person': x[0], 'htid': ny_auth_pull_dict[x[0]]})
for row in x[1:]:
    df2 = pd.DataFrame({'person': row, 'htid': ny_auth_pull_dict[row]})
    ny_auth_cl_df = pd.concat([ny_auth_cl_df, df2])
    
ny_auth_cl_df.head(15)

                        htid                      person
0         hvd.32044011813458   Stevens, Doris 1892-1963
1         hvd.32044031715816   Stevens, Doris 1892-1963
2         mdp.39015080257093   Stevens, Doris 1892-1963
3         hvd.32044087355707   Stevens, Doris 1892-1963
4         iau.31858030672558   Stevens, Doris 1892-1963
5         mdp.39015009198824   Stevens, Doris 1892-1963
0         mdp.39015032766316             Willis, Ellen.
1         mdp.39015032766316             Willis, Ellen.
2         mdp.39015048768363             Willis, Ellen.
3         mdp.39015032766316             Willis, Ellen.
4         mdp.39015032766316             Willis, Ellen.
0         iau.31858023968278                Hale, Ruth.
0   aeu.ark:/13960/t4rj69w6s  Glaspell, Susan 1882-1948
1  coo1.ark:/13960/t6pz5s55c  Glaspell, Susan 1882-1948
2               uc1.$b242960  Glaspell, Susan 1882-1948

In [139]:
x = [item[0] for item in chi_auth_pull_dict.items()]
chi_auth_cl_df = pd.DataFrame({'person': x[0], 'htid': chi_auth_pull_dict[x[0]]})
for row in x[1:]:
    df2 = pd.DataFrame({'person': row, 'htid': chi_auth_pull_dict[row]})
    chi_auth_cl_df = pd.concat([chi_auth_cl_df, df2])
    
chi_auth_cl_df.head(15)

                       htid                                             person
0  loc.ark:/13960/t14m9xt96  Breckinridge, Sophonisba Preston 1866-1948, [f...
0        mdp.39015033639777                                   Brown, Corinne.
1        mdp.39015059789282                                   Brown, Corinne.
2              uc1.$b276033                                   Brown, Corinne.
0        nyp.33433023037900                 Lathrop, Julia Clifford 1858-1932
0  loc.ark:/13960/t14m9xt96       Abbott, Edith 1876-1957. [from old catalog]
0              uiuc.2436136                  Yarros, Rachelle Skidelski 1869-
0        inu.30000042386536                           Anderson, Mary B. 1939-
1        inu.30000042386536                           Anderson, Mary B. 1939-
2           uc1.l0078858131                           Anderson, Mary B. 1939-
3        mdp.39015032643754                           Anderson, Mary B. 1939-
4        uc1.31822007650062                           Anderson, Mary B. 1939-
5        uc1.32106010534730                           Anderson, Mary B. 1939-
0  gri.ark:/13960/t4km36v25                                 Boyd, Neva Leona.
1        osu.32435005345004                                 Boyd, Neva Leona.

In [141]:
x = [item[0] for item in chi_org_pull_dict.items()]
chi_org_cl_df = pd.DataFrame({'org': x[0], 'htid': chi_org_pull_dict[x[0]]})
for row in x[1:]:
    df2 = pd.DataFrame({'org': row, 'htid': chi_org_pull_dict[row]})
    chi_org_cl_df = pd.concat([chi_org_cl_df, df2])
    
chi_org_cl_df.head(15)

                 htid                                                org
0  coo.31924002334971  Amalgamated Clothing Workers of America, Local...
0  coo.31924001734064  Coalition of Labor Union Women Convention, Was...
0  mdp.39015072116984            Association for Family Living, Chicago
0  inu.32000007711684             La Leche League of Franklin Park, Inc
0        chi.40798587  Industrial Workers of the World Convention (2n...
0  mdp.39015080267209  Amalgamated clothing workers of America and Me...
0  ien.35556021807136  League of Women Voters of Cook County (Cook Co...
1  ien.35556021885181  League of Women Voters of Cook County (Cook Co...
2  ien.35556020525689  League of Women Voters of Cook County (Cook Co...
3  ien.35556026356584  League of Women Voters of Cook County (Cook Co...
4  ien.35556026700013  League of Women Voters of Cook County (Cook Co...
5  ien.35556018017061  League of Women Voters of Cook County (Cook Co...
6  ien.35556020525689  League of Women Voters of Cook County (Cook Co...
7  ien.35556021878988  League of Women Voters of Cook County (Cook Co...
8  ien.35556022999098  League of Women Voters of Cook County (Cook Co...

In [144]:
ny_org_cl_df.head(75)

,htid,org
0,hvd.32044096984315,"Henry Street Settlement (New York, N.Y.)"
1,mdp.39015032973870,"Henry Street Settlement (New York, N.Y.)"
2,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
3,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
4,uc1.b2825126,"Henry Street Settlement (New York, N.Y.)"
5,uiug.30112063825167,"Henry Street Settlement (New York, N.Y.)"
6,uiuo.ark:/13960/t3033k24n,"Henry Street Settlement (New York, N.Y.)"
7,mdp.39015032973870,"Henry Street Settlement (New York, N.Y.)"
8,uc1.32106001402830,"Henry Street Settlement (New York, N.Y.)"
0,mdp.39015082092431,"League of Women Voters of Cook County, Ill"
0,umn.31951001536118z,Progressive Party National Convention: (1st : ...
0,coo.31924002335606,International Ladies' Garment Workers' Union L...
1,umn.31951002031948a,International Ladies' Garment Workers' Union L...
0,uc1.b3865194,"Henry Street Settlement, New York Hamilton Hou..."
0,coo.31924052338997,League of Women Voters of Albany County (Alban...
0,hvd.32044087387908,"Sorosis (New York, N.Y.)"
1,hvd.32044013641089,"Sorosis (New York, N.Y.)"
2,hvd.hn6ixd,"Sorosis (New York, N.Y.)"
0,inu.30000055098549,International Ladies' Garment Workers' Union L...
1,inu.30000055098549,International Ladies' Garment Workers' Union L...
2,inu.30000055098549,International Ladies' Garment Workers' Union L...
0,coo.31924000838536,International Ladies' Garment Workers' Union L...
1,coo.31924054286210,International Ladies' Garment Workers' Union L...
2,coo.31924054286228,International Ladies' Garment Workers' Union L...
3,coo.31924054286236,International Ladies' Garment Workers' Union L...
4,coo.31924054286202,International Ladies' Garment Workers' Union L...
0,mdp.39015034368798,"Greenwich House (New York, N.Y.)"
1,mdp.39015028060609,"Greenwich House (New York, N.Y.)"
2,umn.31951001519095i,"Greenwich House (New York, N.Y.)"
0,ien.35556020525689,League of Women Voters of Cook County (Cook Co...
1,ien.35556018017061,League of Women Voters of Cook County (Cook Co...
2,ien.35556020525689,League of Women Voters of Cook County (Cook Co...
3,ien.35556021878988,League of Women Voters of Cook County (Cook Co...
4,ien.35556022999098,League of Women Voters of Cook County (Cook Co...
5,ien.35556026700013,League of Women Voters of Cook County (Cook Co...
6,ien.35556021807136,League of Women Voters of Cook County (Cook Co...
7,ien.35556021885181,League of Women Voters of Cook County (Cook Co...
8,ien.35556021878988,League of Women Voters of Cook County (Cook Co...
9,ien.35556022999098,League of Women Voters of Cook County (Cook Co...
10,ien.35556026675447,League of Women Voters of Cook County (Cook Co...
11,ien.35556026356584,League of Women Voters of Cook County (Cook Co...
12,ien.35556026675447,League of Women Voters of Cook County (Cook Co...
13,ien.35556031552870,League of Women Voters of Cook County (Cook Co...
14,ien.35556031552870,League of Women Voters of Cook County (Cook Co...
15,ien.35556021807136,League of Women Voters of Cook County (Cook Co...
16,ien.35556021885181,League of Women Voters of Cook County (Cook Co...
17,ien.35556026356584,League of Women Voters of Cook County (Cook Co...
18,ien.35556026700013,League of Women Voters of Cook County (Cook Co...

In [142]:
ny_org_cl_df.to_csv('ny_org_ben_pull.csv')
ny_auth_cl_df.to_csv('ny_auth_ben_pull.csv')

chi_auth_cl_df.to_csv('chi_auth_ben_pull.csv')
chi_org_cl_df.to_csv('chi_org_ben_pull.csv')